language: python

install:
  - pip install coveralls tox

script:
  - tox

after_success:
  - coveralls

env:
  - TOXENV=django18-py27
  - TOXENV=django18-py33
  - TOXENV=django18-py34
  - TOXENV=django18-py35
  - TOXENV=django19-py27
  - TOXENV=django19-py34
  - TOXENV=django19-py35

matrix:
  allow_failures:
    # - env: TOXENV=django18-py27
    - env: TOXENV=django18-py33
    - env: TOXENV=django18-py34
    - env: TOXENV=django18-py35
    - env: TOXENV=django19-py27
    - env: TOXENV=django19-py34
    - env: TOXENV=django19-py35
  fast_finish: true
